
---
# Description:
  # This playbook shows how to install an ARCAD fix/patch using Ansible and ibm collection
  # ibm.power_ibmi (ansible for i)
  
# Restriction: 
  # You must have *ALLOBJ special authorities to use this playbook (see inventory to define the profile to use 
  # that should be configured with ssh

# Parameters:
  # fixpath : not required /tmp assumed by default ansible server path containing the fix FMxxxxxx.dta file
  # fix : not required the fix FM210260 will be installed
  # ext : not required assuming the extension is .DTA
 
# Example:
  # ansible-playbook -i hosts ARCAD_Master_install.yml -e "target_ibmi=your_ibmi"

- hosts: '{{ target_ibmi }}'
  gather_facts: no
  collections:
   - ibm.power_ibmi
  vars:
      fixpath: "/tmp/"
      fix: "FM210260"
      ext: ".DTA"
  
  tasks:
 
    - name: copy fix to the target
      copy: 
        src: "{{ fixpath }}{{ fix }}{{ ext}}"
        dest: "{{ fixpath}}{{ fix }}{{ ext }}"

    - name: create savf into QGPL
      ibmi_cl_command:
        cmd: CRTSAVF QGPL/{{ fix }} 
      ignore_errors: yes
      
    - name: delete fix library if exists
      ibmi_cl_command:
        cmd: DLTLIB {{fix}}
      ignore_errors: yes
      

    - name: copy into a savefile
      ibmi_cl_command:
        cmd: cpyfrmstmf  FROMSTMF('{{fixpath}}{{ fix }}{{ ext }}') TOMBR('/QSYS.LIB/QGPL.LIB/{{ fix }}.file') MBROPT(*REPLACE) 
        joblog: true

    - name: restore fix library
      ibmi_cl_command:
        cmd: RSTLIB SAVLIB({{ fix }})  DEV(*SAVF) SAVF(QGPL/{{ fix }})  MBROPT(*ALL) STRJRN(*NO) ALWOBJDIF(*ALL) 
        joblog: true
        

    - name: regenerate macro-command RCVFIX
      ibmi_cl_command:
        cmd: AGENMACCMD MACRO({{ fix }}/RCVFIX)
        joblog: true

    - name: install fix
      ibmi_cl_command:
        cmd: "{{ fix }}/RCVFIX LIB({{ fix }})"
        joblog: true     