
---
# Description:
  # This playbook shows how to install an ARCAD Builder using Ansible
  
# Restriction: 
  # You must have *ALLOBJ and *SECADM special authorities to use this playbook (see inventory to define the profile to use 
  # that should be configured with ssh

# Parameters:
  # target_ibmi : replace by an ibmi host defined in the ansible inventory

# Requirements:
  # mandatory to have a properties file to avoid to answer at each question during installation
  # example of properties content
  # afs.starter.library will contain the command to start and stop the ARCAD builder server
  # ibmi.password should be crypted in base64
  # install.directory defined where the ARCAD Builder server will be installed
  # ibmi.target will define the connection to the server used by the ARCAD Builder web console
  # mandatory to call the properties file builder-server.properties
  # '''
  #   afs.https.port=52520                                    
  #   afs.starter.instance=BUILDER                            
  #   afs.starter.library=AFSSTARTER                            
  #   afs.user=ARCAD_PGMR                                     
  #   install.directory=/home/sgomes/containers/Builder-Server
  #   afs.starter.iasp="*SYSBAS"                                
  #   afs.http.port=5252                                      
  #   arcad.jobq.library=ARCAD_SYS
  #   arcad.jobq=ARCAD_CTL                                                          
  # '''

# Example:
  # ansible-playbook -i hosts ARCAD_Builder_install.yml -e "target_ibmi=your_ibmi"
  

- hosts: '{{ target_ibmi }}'
  gather_facts: no
  
  vars:
    destpath: "/tmp/Setup_Builder-Server-13.2.0_IBMi.jar"
    tmpdir: "/tmp/"

  tasks:

  - name: Copy file from Ansible Master to target IBM i 
    copy:
      src: "{{destpath}}"
      dest: "{{destpath}}"

  - name: Creating the properties file
    shell: "echo \"afs.https.port=52520\nafs.starter.instance=BUILDER\nafs.starter.library=AFSSTARTER\nafs.user=ARCAD_PGMR\ 
    \ninstall.directory=/opt/Builder-Server\nafs.starter.iasp=*SYSBAS\nafs.http.port=5252\narcad.jobq.library=ARCAD_SYS\
    \narcad.jobq=ARCAD_CTL\n\" > {{tmpdir}}builder-server.properties"

  - name: installation
    shell: "cd /tmp && java -jar {{destpath}}"     
    
