---
# Description:
  # This playbook shows how to create and load a sample application for MERLIN project
  # ibm.power_ibmi (ansible for i)
  
# Restriction: 
  # You must have *ALLOBJ and *SECADM special authorities to use this playbook (see inventory to define the profile to use 
  # that should be configured with ssh

# Parameters:
  # prefix: application name should be 6 characters MAX because we add some suffixes to create the application libraries

# Example:
  # ansible-playbook -i hosts ARCAD_sample_application.yml -e "target_ibmi=your_ibmi"
  

- hosts: '{{ target_ibmi }}'
  gather_facts: no
  collections:
   - ibm.power_ibmi

  vars:
    prefix: "MERLIN"
    
    

  
  tasks:
    - name: Create the demo object library
      ibmi_cl_command: 
        cmd: CRTLIB LIB({{prefix}}_OBJ) TYPE(*TEST) TEXT('Merlin Sample Objects')    
        joblog: true

    - name: Restore the object library
      ibmi_cl_command: 
        cmd: RSTOBJ OBJ(*ALL) SAVLIB(SAMPLE_OBJ) DEV(*SAVF) SAVF(ARCAD_DEMO/SAMPLE_OBJ) MBROPT(*ALL) RSTLIB({{prefix}}_OBJ)                                                           
        joblog: true

    - name: Create the demo data library
      ibmi_cl_command: 
        cmd: CRTLIB LIB({{prefix}}_DTA) TYPE(*TEST) TEXT('Merlin Sample Files')    
        joblog: true

    - name: Restore the data library
      ibmi_cl_command: 
        cmd: RSTOBJ OBJ(*ALL) SAVLIB(SAMPLE_DTA) DEV(*SAVF) SAVF(ARCAD_DEMO/SAMPLE_DTA) MBROPT(*ALL) RSTLIB({{prefix}}_DTA)                                                            
        joblog: true

                                                                  
    - name: Create the demo source library
      ibmi_cl_command: 
        cmd: CRTLIB LIB({{prefix}}_SRC) TYPE(*TEST) TEXT('Merlin Sample Sources')    
        joblog: true

    - name: Restore the source library
      ibmi_cl_command: 
        cmd: RSTOBJ OBJ(*ALL) SAVLIB(SAMPLE_SRC) DEV(*SAVF) SAVF(ARCAD_DEMO/SAMPLE_SRC) MBROPT(*ALL) RSTLIB({{prefix}}_SRC)                                                            
        joblog: true

    - name: create the MERLIN demo application
      ibmi_cl_command: 
        cmd: ADCLAPP APP({{prefix}}) APPTEXT('Merlin Demo') APPRESP(ARCAD_PGMR) OPELIB({{prefix}}_OBJ {{prefix}}_DTA {{prefix}}_SRC) LIBPREFIX(MRL) PMTLIBLIST(*NO)   
        joblog: true

    - name: adding ARCAD_DEMO in the application library list
      ibmi_cl_command: 
        cmd: ACHGLIBLBL APP({{prefix}}) LIB(ARCAD_DEMO) POSITION(*LAST)
        joblog: true

    - name: genering sources members for objects in sample application for Merlin project
      ibmi_cl_command: 
        cmd: GENSCMSRC APP({{prefix}}) SRCLIB({{prefix}}_SRC)  
        joblog: true

    - name: renaming clause copy to RPGLEINC
      ibmi_cl_command: 
        cmd: CHGPFM FILE({{prefix}}_SRC/QPROTOSRC) MBR({{item}}) SRCTYPE(RPGLEINC)          
        joblog: true
      with_items:
      - APICALL
      - ARTICLE
      - COUNTRY
      - CUSTOMER
      - FAMILLY
      - LOG
      - PARAMETER
      - PROVIDER
      - VAT

    - name: adding ARCAD_ENG in library list 
      ibmi_cl_command: 
        cmd: ARCAD_ENG/ACHGLIBLBL ACTION(*ADDMOV) APP({{prefix}}) ENV(*NONE) VERSION(*NONE) LIB(ARCAD_ENG) POSITION(*FIRST) LIBTYPE(*SYSLIB)                               
        joblog: true
                               
    - name: updating AARCLBIF1 file for application level
      ibmi_cl_command: 
        cmd: AEXCSQL SQLSTM('update arcad_prd/AARCLBIF1 set lbi_clocty = ''2'' WHERE LBI_ILBL in (select app_ilbl from arcad_prd/AARCAPPF1 where app_capp = ''{{prefix}}'')  and lbi_jlib =''ARCAD_ENG''')  
        joblog: true

    - name: loading MERLIN application 
      ibmi_cl_command: 
        cmd: DECLARE3 APP({{prefix}})   
        joblog: true
                                                                      
    - name: creating the Dev environment 
      ibmi_cl_command: 
        cmd: ADCLENV APP({{prefix}}) ENV(DEV) ENVTYPE(*DEV) IMPLTYPE(*NRM) LIBPREFIX(MRLD)      
        joblog: true

    - name: adding ARCAD_ENG in library list for DEV environment 
      ibmi_cl_command: 
        cmd: ARCAD_ENG/ACHGLIBLBL ACTION(*ADDMOV) APP({{prefix}}) ENV(DEV) VERSION(*NONE) LIB(ARCAD_ENG) POSITION(*FIRST) LIBTYPE(*SYSLIB)                               
        joblog: true        

    - name: creating the UAT environment 
      ibmi_cl_command: 
        cmd: ADCLENV APP({{prefix}}) ENV(UAT) ENVTYPE(*TST) IMPLTYPE(*DTA) LIBPREFIX(MRLT) OPELIB({{prefix}}OBJT {{prefix}}DTAT {{prefix}}SRCT)      
        joblog: true
         
    - name: adding ARCAD_ENG in library list for UAT environment 
      ibmi_cl_command: 
        cmd: ARCAD_ENG/ACHGLIBLBL ACTION(*ADDMOV) APP({{prefix}}) ENV(UAT) VERSION(*NONE) LIB(ARCAD_ENG) POSITION(*FIRST) LIBTYPE(*SYSLIB)                               
        joblog: true        
                                 
    - name: updating AARCLBIF1 file for environment level
      ibmi_cl_command: 
        cmd: AEXCSQL SQLSTM('update arcad_prd/AARCLBIF1 set lbi_clocty = ''2'' WHERE LBI_ILBL in (select env_ilbl from arcad_prd/AARCENVF1 where env_capp = ''{{prefix}}'')  and lbi_jlib =''ARCAD_ENG''')  
        joblog: true

    - name: updating general parameters to allow checkout from SCM
      ibmi_cl_command: 
        cmd: AEXCSQL SQLSTM('update arcad_prd/aarmvtyf1 set VTY_CCHKOU = ''*SCM'' WHERE VTY_CAPP = '' ''')    
        joblog: true
