---
# Description:
  # This playbook shows how to install rpm package using Ansible
  
# Restriction: 
  # You must have *ALLOBJ special authorities to use this playbook (see inventory to define the profile to use 
  # that should be configured with ssh

# Parameters:
  # package_name : package to install
 
# Example:
  # ansible-playbook -i hosts ARCAD_rpm_install.yml -e "target_ibmi=your_ibmi"

- hosts: '{{ target_ibmi }}'
  gather_facts: no 
   
  vars:
      destpath: "/tmp/"
      package_name: "eliasCLI"
      ext: "1.0.0-SNAPSHOT.ibmi7.4.ppc64.rpm"
      destpath: "/tmp/"

  tasks:

  - name: Copy file from Ansible Master to target IBM i 
    copy:
      src: "{{destpath}}/{{package_name}}-{{ext}}"
      dest: "{{destpath}}/{{package_name}}-{{ext}}"

  - name: Verify {{ item }} installed
    raw: /QOpensys/pkgs/bin/yum list installed | grep {{ package_name }}
    register: package_query_result
    ignore_errors: true

  - name: Install {{ item }} if it is not installed
    raw: /QOpensys/pkgs/bin/yum install {{destpath}}/{{package_name}}-{{ext}} -y
    when: package_name not in package_query_result.stdout