---
# Description:
  # This playbook shows how to install rpm package using Ansible
  
# Restriction: 
  # You must have *ALLOBJ special authorities to use this playbook (see inventory to define the profile to use 
  # that should be configured with ssh

# Parameters:
  # package_name : package to install
 
# Example:
  # ansible-playbook -i hosts ARCAD_rpm_install.yml -e "target_ibmi=your_ibmi"

- hosts: '{{ target_ibmi }}'
  gather_facts: no 
   
  vars:
    package_name: "eliasCLI"

  tasks:

  - name: Verify {{ package_name }} installed
    raw: /QOpensys/pkgs/bin/yum list installed | grep {{ package_name }}
    register: package_query_result
    ignore_errors: true

  - name: uninstall {{ package_name }} 
    raw: /QOpensys/pkgs/bin/yum remove {{package_name}} -y
    when: package_name in package_query_result.stdout