---
# Description:
  # This playbook shows how to delete an application and object libraries linked to it
  # ibm.power_ibmi (ansible for i)
  
# Restriction: 
  # You must have ARCAD administrator authority

# Parameters:
  # app: application name

# Example:
  # ansible-playbook -i hosts ARCAD_delete_application.yml -e "target_ibmi=your_ibmi"
  

- hosts: '{{ target_ibmi }}'
  gather_facts: no
  collections:
   - ibm.power_ibmi

  vars:
    app: "MERLIN"
    
    

  
  tasks:
    - name: delete the application {{app}}
      ibmi_cl_command: 
        cmd: ADLTAPP APP({{app}})  
        joblog: true

    - name: Delete the application library and tests libraries
      ibmi_cl_command: 
        cmd: DLTLIB LIB({{item}}) 
        joblog: true
      ignore_errors: yes        
      with_items:
      - '{{app}}_OBJ'
      - '{{app}}_DTA'
      - '{{app}}_SRC'
      - '{{app}}OBJT'
      - '{{app}}SRCT'
      - '{{app}}DTAT'



 
                                 