
---
# Description:
  # This playbook shows how to uninstall a Jetty server using Ansible

# Parameters:
  # target_ibmi : replace by an ibmi host defined in the ansible inventory
  # jettydir : where jetty is installed
  # jettylib : jetty library


# Example:
  # ansible-playbook -i hosts Jetty_uninstall.yml -e "target_ibmi=your_ibmi"


- hosts: '{{ target_ibmi }}'
  gather_facts: no
  collections:
   - ibm.power_ibmi
  vars:
    jettydir: "/opt/jetty"
    jettylib: "JETTY"

  tasks:

  - name: stop  JETTY server
    ibmi_cl_command: 
      cmd: JETTY/ENDJTYSVR  
      joblog: true
    ignore_errors: yes  

  - name: endsbs JETTY sybsystem
    ibmi_cl_command: 
      cmd: ENDSBS SBS({{jettylib}}) OPTION(*IMMED)  
      joblog: true
    ignore_errors: yes    

  - name: clear jetty outq 
    ibmi_cl_command: 
      cmd: CLRJOBQ JOBQ({{jettylib}}/{{jettylib}})  
      joblog: true
    ignore_errors: yes     

  - name: delete jetty library
    ibmi_cl_command: 
      cmd: DLTLIB LIB({{jettylib}})  
      joblog: true
    ignore_errors: yes         

  - name: delete jetty directory
    shell: "rm -rf {{jettydir}}"     
    ignore_errors: yes         
    